# Generated by Django 3.0.3 on 2020-04-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('category_id', models.IntegerField()),
                ('category', models.TextField()),
                ('currencycode', models.TextField(blank=True, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('goal', models.IntegerField()),
                ('donators', models.IntegerField()),
                ('days_active', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_beneficiary', models.BooleanField()),
                ('turn_off_donations', models.BooleanField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_first_name', models.TextField(blank=True, null=True)),
                ('user_last_name', models.TextField(blank=True, null=True)),
                ('user_profile_url', models.TextField(blank=True, null=True)),
                ('deactivated', models.BooleanField(blank=True, null=True)),
                ('campaign_image_url', models.TextField(blank=True, null=True)),
                ('launch_date', models.TextField(blank=True, null=True)),
                ('campaign_hearts', models.IntegerField()),
                ('social_share_total', models.IntegerField()),
                ('social_share_last_update', models.TextField(blank=True, null=True)),
                ('location_city', models.TextField(blank=True, null=True)),
                ('location_country', models.TextField(blank=True, null=True)),
                ('location_zip', models.TextField(blank=True, null=True)),
                ('charity_valid', models.BooleanField(blank=True, null=True)),
                ('charity_npo_id', models.TextField(blank=True, null=True)),
                ('charity_name', models.TextField(blank=True, null=True)),
                ('is_fulfilled_numeric', models.BooleanField(blank=True, null=True)),
                ('percent_fulfilled', models.TextField(blank=True, null=True)),
                ('success', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
